version: '3.9'

services:
  db:
    image: mysql:8.0
    container_name: devsusql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: devsu_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: "AdminDevsu2026$"
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5

  cliente:
    build:
      context: ./devsu-client
    container_name: cliente_service
    ports:
      - "3333:3333"
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://devsusql:3306/devsu_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: "AdminDevsu2026$"

  account:
    build:
      context: ./devsu-account
    container_name: account_service
    ports:
      - "4444:4444"
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://devsusql:3306/devsu_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: "AdminDevsu2026$"

volumes:
  db_data: